version: '3.7'

x-redash-service: &redash-service
  image: redash/redash:latest
  depends_on:
  - postgres
  - redis
  env_file: redash.env
  restart: always

services:

  redis:
    image: redis:latest
    restart: always

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

    logging: 
      options:
        max-size: 10m
        max-file: "3"

  mysql:
    image: mysql:5.7.27
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
    volumes:
        - ./op_files:/var/lib/mysql-files/
    ports:
        - "42060:3306"

  webserver:
    build: ./dockerfiles
    restart: always
    depends_on:
      - postgres
      - mysql
    environment:
      - INSTALL_MYSQL=y
      - LOAD_EX=n
      - EXECUTOR=Local
    volumes:
      - .airflow_/dags:/usr/local/airflow/dags
      - ./scripts/python:/usr/local/airflow/includes
      - .airflow_/logs:/opt/airflow/logs
      - .airflow_/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver

  server:
    <<: *redash-service
    command: server
    ports:
      - 5000:5000
    environment:
      REDASH_WEB_WORKERS: 4
  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2