version: '2'

x-redash-service: &redash-service
  image: redash/redash:latest
  depends_on:
    - redis2
  env_file: ./.env/redash.env
  restart: always

services:
  server:
    <<: *redash-service
    command: server
    ports:
      - 11111:5000
    environment:
      REDASH_WEB_WORKERS: 4
  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2

  redis2:
    image: redis:latest
    restart: always

networks: 
  default: 
    external: 
      name: local_network_1