services:
  mysql:
      image: mysql:5.7.27
      environment:
        - MYSQL_ROOT_PASSWORD=mysql
      volumes:
          - ../data:/var/lib/mysql-files/
          - ../scripts/sql/init_mysql.sql:/docker-entrypoint-initdb.d/init_mysql.sql
      ports:
          - "42060:3306"

networks: 
  default: 
    external: 
      name: local_network_1