FROM puckel/docker-airflow:1.10.9
COPY requirements.txt /requirements.txt
RUN export PATH="/usr/local/airflow/.local/bin:$PATH"
RUN pip install --user --upgrade pip
RUN pip install --no-cache-dir --user -r /requirements.txt
RUN export PATH="/usr/local/airflow/.local/bin:$PATH"