version: '3.6'
services: 
    postgres:
        build: ./dockerfiles/postgres
        restart: always
        environment: 
            - DATABASE_HOST=127.0.0.1
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=root  
            - POSTGRES_HOST_AUTH_METHOD=trust

        ports: 
            - "5432:5432"
        volumes: 
            - ../scripts/sql/postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
            
    pgadmin-compose:
        image: dpage/pgadmin4
        environment: 
            PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "test123!"
        ports: 
            - "16543:80"
        depends_on: 
            - postgres    

networks: 
  default: 
    external: 
      name: local_network_1